### ISSUE TITLE
StructureComponents showing up in OnKilled hook

### ISSUE THREAD

**Issue by bgourlie** [OxideMod/1.18#37]
Any idea why structures would be showing up on the OnKilled hook?  For example:

    2:36 AM: attacker:{id=(WoodPillar(Clone) (StructureComponent)),idMain=(WoodPillar(Clone) (StructureComponent))}: -149618
    2:36 AM: victim:{id=(WoodPillar(Clone) (StructureComponent)),idMain=(WoodPillar(Clone) (StructureComponent))}: -149618
    2:36 AM: sender:[WoodPillar(Clone) (ProtectionTakeDamage): health=0]: -149616
    2:36 AM: status:WasKilled: 1
    2:36 AM: damageTypes0: 0
    2:36 AM: amount: 581.68536376953
    2:36 AM: extraData: nil
    2:36 AM: bodyPart: Undefined: 0

**Comment by lukespragg** [comment]
With Oxide 2 being available now, I don't see this being resolved.
